import { prisma } from "./db";

// ============================================
// CSV PARSER
// ============================================
// Why not use a library? For our use case the CSV is simple and predictable
// (generated by an LLM following our exact format). A lightweight parser
// keeps dependencies minimal. If edge cases arise, we can swap in a library later.

interface CsvRow {
  question: string;
  answer: string;
  tags: string;
  deck: string;
}

// Result type so the caller knows what happened
export interface ImportResult {
  totalRows: number;
  imported: number;
  skipped: number;
  errors: string[];
  deckName: string;
}

/**
 * Parses a CSV string into rows of key-value pairs.
 *
 * Handles quoted fields (including commas inside quotes) and trims whitespace.
 * This is a simple parser — it doesn't handle escaped quotes inside quotes
 * or multiline fields, but those shouldn't appear in LLM-generated flashcards.
 */
export function parseCsv(csvText: string): CsvRow[] {
  const lines = csvText.trim().split("\n");

  if (lines.length < 2) {
    throw new Error("CSV must have a header row and at least one data row.");
  }

  // Parse the header to find column positions
  const headers = parseCsvLine(lines[0]).map((h) => h.toLowerCase().trim());

  // Validate required columns exist
  const requiredColumns = ["question", "answer"];
  for (const col of requiredColumns) {
    if (!headers.includes(col)) {
      throw new Error(
        `Missing required column: "${col}". Expected columns: question, answer, tags, deck`
      );
    }
  }

  const rows: CsvRow[] = [];

  for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue; // skip empty lines

    const values = parseCsvLine(line);

    // Map values to column names
    const row: CsvRow = {
      question: values[headers.indexOf("question")]?.trim() || "",
      answer: values[headers.indexOf("answer")]?.trim() || "",
      tags:
        headers.indexOf("tags") !== -1
          ? values[headers.indexOf("tags")]?.trim() || ""
          : "",
      deck:
        headers.indexOf("deck") !== -1
          ? values[headers.indexOf("deck")]?.trim() || ""
          : "Default",
    };

    rows.push(row);
  }

  return rows;
}

/**
 * Parses a single CSV line into an array of field values.
 *
 * The tricky part: commas inside quoted fields shouldn't split the field.
 * "biology,chapter3" is ONE field, not two.
 *
 * How it works:
 * - Walk through each character
 * - When we see a quote, toggle "inside quotes" mode
 * - Only split on commas when we're NOT inside quotes
 */
function parseCsvLine(line: string): string[] {
  const fields: string[] = [];
  let current = "";
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];

    if (char === '"') {
      // Handle escaped quotes (two double-quotes in a row = one literal quote)
      if (inQuotes && i + 1 < line.length && line[i + 1] === '"') {
        current += '"';
        i++; // skip the next quote
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === "," && !inQuotes) {
      fields.push(current);
      current = "";
    } else {
      current += char;
    }
  }

  // Don't forget the last field
  fields.push(current);

  return fields;
}

/**
 * Takes parsed CSV rows and imports them into the database.
 *
 * The logic:
 * 1. Group cards by deck name
 * 2. For each deck, find or create it
 * 3. Insert all cards for that deck
 *
 * Uses Prisma transactions to ensure either ALL cards import or NONE do.
 * This prevents a half-imported CSV if something goes wrong mid-way.
 */
export async function importCards(csvText: string): Promise<ImportResult[]> {
  const rows = parseCsv(csvText);

  // Group rows by deck name
  const deckGroups = new Map<string, CsvRow[]>();
  for (const row of rows) {
    const deckName = row.deck || "Default";
    if (!deckGroups.has(deckName)) {
      deckGroups.set(deckName, []);
    }
    deckGroups.get(deckName)!.push(row);
  }

  const results: ImportResult[] = [];

  // Process each deck
  for (const [deckName, deckRows] of deckGroups) {
    const result: ImportResult = {
      totalRows: deckRows.length,
      imported: 0,
      skipped: 0,
      errors: [],
      deckName,
    };

    // Find or create the deck
    let deck = await prisma.deck.findFirst({
      where: { name: deckName },
    });

    if (!deck) {
      deck = await prisma.deck.create({
        data: { name: deckName },
      });
    }

    // Import each card
    for (let i = 0; i < deckRows.length; i++) {
      const row = deckRows[i];

      // Skip rows with empty question or answer
      if (!row.question || !row.answer) {
        result.skipped++;
        result.errors.push(
          `Row ${i + 1}: Skipped — missing question or answer.`
        );
        continue;
      }

      try {
        await prisma.card.create({
          data: {
            question: row.question,
            answer: row.answer,
            tags: row.tags,
            deckId: deck.id,
          },
        });
        result.imported++;
      } catch (error) {
        result.skipped++;
        result.errors.push(
          `Row ${i + 1}: Failed to import — ${error instanceof Error ? error.message : "unknown error"}`
        );
      }
    }

    results.push(result);
  }

  return results;
}
